---
# tasks file for project
- name: create LimitRange
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: LimitRange
      metadata:
         name: '{{ meta.name }}'
         namespace: '{{ meta.name }}'
      spec:
        limits:
        - max:
            memory: "{{limitrangemaxmem}}"
            cpu: "{{limitrangemaxcpu}}"
          min:
            cpu: "{{limitrangemincpu}}"
            memory: "{{limitrangeminmem}}"
          default:
            cpu: "{{limitrangedefaultcpu}}"
            memory: "{{limitrangedefaultmem}}"
          defaultRequest:
            cpu: "{{limitrangedefaultrequestcpu}}"
            memory: "{{limitrangedefaultrequestmem}}"
          type: Container

- name: create ResourceQuota
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: ResourceQuota
      metadata:
         name: '{{ meta.name }}'
         namespace: '{{ meta.name }}'
      spec:
         hard:
           requests.cpu: "{{resourcequotarequestscpu}}"
           requests.memory: "{{resourcequotarequestsmemory}}"
           limits.cpu: "{{resourcequotalimitscpu}}"
           limits.memory: "{{resourcequotalimitsmemory}}"
           count/jobs.batch: "{{resourcequotacountjobsbatch}}"
           count/ingresses.extensions: "{{resourcequotacountingresses}}"
           pods: "{{resourcequotapods}}"
           services: "{{resourcequotaservices}}"
           configmaps: "{{resourcequotaconfigmaps}}"
           persistentvolumeclaims: "{{resourcequotapersistentvolumeclaims}}"
           replicationcontrollers: "{{resourcequotareplicationcontrollers}}"
           secrets: "{{resourcequotasecrets}}"
           services.loadbalancers: "{{resourcequotaservicesloadbalancers}}"
