---
# tasks file for project
- name: create Project cr
  community.kubernetes.k8s:
    definition:
      apiVersion: project.xddevelopment.com/v1alpha1
      kind: Project
      metadata:
        name: '{{ meta.name }}'
        namespace: cluster-operators
      spec:
        # Add fields here
        resourcequotarequestscpu: "200"
        resourcequotarequestsmemory: 200Gi
        resourcequotalimitscpu: "200"
        resourcequotalimitsmemory: 300Gi
        resourcequotacountjobsbatch: 1000
        resourcequotacountingresses: 50
        resourcequotapods: 1000
        resourcequotaservices: "100"
        resourcequotaconfigmaps: "500"
        resourcequotapersistentvolumeclaims: "100"
        resourcequotareplicationcontrollers: "500"
        resourcequotasecrets: "100"
        resourcequotaservicesloadbalancers: "50"
  when:  (meta.name  != 'kube-system') and (meta.name  != 'kube-node-lease') and (meta.name  != 'kube-public') and (meta.name  != 'monitoring')
