---
# tasks file for project
- name: create LimitRange
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: LimitRange
      metadata:
         name: '{{ meta.name }}'
         namespace: '{{ meta.name }}'
      spec:
        limits:
        - max:
            memory: "{{limitrangemaxmem}}"
            cpu: "{{limitrangemaxcpu}}"
          min:
            cpu: "{{limitrangemincpu}}"
            memory: "{{limitrangeminmem}}"
          default:
            cpu: "{{limitrangedefaultcpu}}"
            memory: "{{limitrangedefaultmem}}"
          defaultRequest:
            cpu: "{{limitrangedefaultrequestcpu}}"
            memory: "{{limitrangedefaultrequestmem}}"
          type: Container
