---
# tasks file for project
- name: create LimitRange
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: LimitRange
      metadata:
         name: '{{ meta.name }}'
         namespace: '{{ meta.name }}'
      spec:
        limits:
        - max:
            memory: 30Gi
            cpu: "20000m"
          min:
            cpu: "50m"
            memory: 50Mi
          default:
            cpu: "1000m"
            memory: 1000Mi
          defaultRequest:
            cpu: "100m"
            memory: 100Mi
          type: Container
